### ISSUE TITLE
Grinding Stats

### ISSUE THREAD

**Issue by drekdrek** [openplanet-nl/plugin-signing#148]
## Plugin description
This plugin keeps track of and displays:

- Time played the track
- Resets
- Finishes

these are tracked for total on the track and in the current session.
you can pick and choose what you would like on the UI.

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
no

## Did you use `Permissions.as`?
no

## Attach your plugin
[Grinding Stats.zip](https://github.com/openplanet-nl/plugin-signing/files/7774758/Grinding.Stats.zip)

**Comment by codecat** [comment]
Tip: You can use `Time::Now` instead of `network.PlaygroundClientScriptAPI.GameTime` as well.

Tip 2: You didn't add a `siteid` to `info.toml`. If you want auto-updating to work, this is required. On Openplanet.nl you can create a file as a draft, which allocates a new site ID for you.

Anyway, looks good 👍 

[GrindingStats.zip](https://github.com/openplanet-nl/plugin-signing/files/7775195/GrindingStats.zip)
