### ISSUE TITLE
Odometer

### ISSUE THREAD

**Issue by RuurdBijlsma** [openplanet-nl/plugin-signing#152]
## Plugin description
Shows how far you've driven in a run like in older games.

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
no

## Did you use `Permissions.as`?
no

## Attach your plugin
[Odometer.zip](https://github.com/openplanet-nl/plugin-signing/files/7786717/Odometer.zip)

**Comment by codecat** [comment]
In the future, consider adding Dashboard as a dependency for this, so that you can get the viewing player w/o having to copy the Vehicle/SceneVis scripts to your own plugin, and can rely on Dashboard's updates to keep that code stable.

[Odometer.zip](https://github.com/openplanet-nl/plugin-signing/files/7792775/Odometer.zip)
