### ISSUE TITLE
Extra leaderboard position 1.0

### ISSUE THREAD

**Issue by Banalian** [openplanet-nl/plugin-signing#189]
## Plugin description

![image](https://user-images.githubusercontent.com/64379456/152602487-1e0cdf90-99da-4f09-8bd2-27b0bd644818.png)

Allows you to see the times of more key positions (1st, 10th, 100th, 1000th and 10000th place times)

This can be used to see how far you are from getting a better trophy reward in a TOTD for example.

I plan to add more features, like seeing where your current PB is or have more customization.

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
yes

## Did you use `Permissions.as`?
no

## Attach your plugin
[ExtraLeaderboardPositions.zip](https://github.com/openplanet-nl/plugin-signing/files/8006225/ExtraLeaderboardPositions.zip)

**Comment by codecat** [comment]
What happens if your plugin encounters a map that does not exist on NadeoServices? What happens if you go into the map editor? These might be some things you wanna look into.

Also, you forgot to add `siteid` to `info.toml`, so I've added it for you.

👍 

[ExtraLeaderboardPositions.zip](https://github.com/openplanet-nl/plugin-signing/files/8006769/ExtraLeaderboardPositions.zip)
