### ISSUE TITLE
Best Checkpoints v1.0

### ISSUE THREAD

**Issue by jamesy012** [openplanet-nl/plugin-signing#190]
## Plugin description

![Screenshot 2022-02-05 113024](https://user-images.githubusercontent.com/2156228/152620636-1595e4d5-da70-4275-9374-64e5a9116233.png)

stores the best times between checkpoints and compares them to the current run
with a theoretical best time 
saves those times to file to load when coming back to the map

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
no

## Did you use `Permissions.as`?
no

## Attach your plugin

[BestCheckpoints.zip](https://github.com/openplanet-nl/plugin-signing/files/8007006/BestCheckpoints.zip)

**Comment by codecat** [comment]
If you intend to upload this to openplanet.nl, make sure you create a draft file, put the ID in `info.toml` (`siteid = x`) and add `version = "1.0"` 👍 (This process will become much easier very very soon, sorry about that!)

Otherwise, let me know and I'll sign it regardless!

Also, small note; you're loading the font like this:
```asc
Resources::GetFont(fontFaceToLoad, fontSize, -1, -1, true, true, true);
```
The `true, true, true` means you want all fallback fonts for icons and extended unicode characters, but I don't think you're actually using any icons or unicode characters. This makes loading the font take longer, and also take a lot of unnecessary memory. I'd recommend just doing this, instead:
```asc
Resources::GetFont(fontFaceToLoad, fontSize);
```

**Comment by jamesy012** [comment]
Hey yup sorry didnt quite understand what was needed in the toml

I added those two values to the .toml file and changed the GetFont call
https://openplanet.nl/files/170

[BestCheckpoints.zip](https://github.com/openplanet-nl/plugin-signing/files/8009191/BestCheckpoints.zip)

**Comment by codecat** [comment]
Hey sorry for the delay in this.

General announcement for all current plugin sign requests:

My current plan is to release a brand new Openplanet website tomorrow morning, which will be the new place for the plugin signing process. I won't be signing this right now, but when you see the new website tomorrow, please upload your plugin (to your existing plugin admin page), and we'll start the plugin review process from there! -- If the new site launch doesn't go as planned, I'll sign your plugin tomorrow morning regardless, but fingers crossed nothing goes wrong.. 🤞

**Comment by codecat** [comment]
Another general announcement for all current plugin sign requests:

The new website is now live! Log in to https://openplanet.dev/ and go to the [my plugins page](https://openplanet.dev/plugins/admin) to find your plugin admin panel, or submit a new plugin [here](https://openplanet.dev/plugins/admin/new) if you haven't created one yet. (Draft plugins have been migrated from the old site.)
