### ISSUE TITLE
Splitscreen Collisions v1.1

### ISSUE THREAD

**Issue by Quickxeryz** [openplanet-nl/plugin-signing#94]
## Plugin description
This plugin enables collisions for splitscreen races.

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
no

## Did you use `Permissions.as`?
no

## Attach your plugin
[SplitsceenCollisions.zip](https://github.com/openplanet-nl/plugin-signing/files/7225278/SplitsceenCollisions.zip)

**Comment by codecat** [comment]
Hi, several problems with this plugin:

* It **always** enables collisions, even when not in splitscreen. This could cause a whole slew of problems. I recommend switching this to a menu button (eg. using `UI::MenuItem` in `RenderMenu`).
* In `info.toml` you wrote `siteid` as a string, rather than an integer. This also causes problems.

**Comment by Quickxeryz** [comment]
Thanks for your answer. I've changed the siteid to an integer and have now buttons for enabling and disabling the collisions. 
New version 1.2:
[SplitsceenCollisions.zip](https://github.com/openplanet-nl/plugin-signing/files/7229442/SplitsceenCollisions.zip)

**Comment by codecat** [comment]
Thanks for the fixes! 👍 

[SplitscreenCollisions.zip](https://github.com/openplanet-nl/plugin-signing/files/7229806/SplitscreenCollisions.zip)
